import PRO from "../assets/pro_price.png";
import BUSSINES from "../assets/business_price.png";

export const pricingData = [
  // {
  //   title: "Lite",
  //   description: "Lite Design",
  //   monthlyPrice: Monthlyp1,
  //   annualPrice: Annualyp1,
  //   annualPriceValue: "",
  //   feature1: "Unlimited Books",
  //   feature2: "Access to Designer",
  //   feature3: "Story Analysis Algorithm",
  //   feature4: "Book Cover Template",
  // },
  {
    id: "1",
    title: "Pro",
    description: "Ai Books",
    monthlyPrice: PRO,
    annualPriceText: "$288 Billed Annually",
    // annualPrice: Annualyp2,
    monthlyPriceValue: "24",
    feature1: "Unlimited Books",
    feature2: "Access to Designer",
    feature3: "Story Analysis Algorithm",
    feature4: "Book Cover Template",
    feature5: "Access to all AI features",
  },
  {
    id: "2",
    title: "Enterprise",
    description: "Unlimited Possiblities",
    monthlyPrice: BUSSINES,
    annualPriceText: "$576 Billed Annually",
    // annualPrice: Annualyp3,
    monthlyPriceValue: "48",
    feature1: "Unlimited Books",
    feature2: "Access to Designer",
    feature3: "Story Analysis Algorithm",
    feature4: "Book Cover Template",
    feature5: "Prompt Library Guide",
    feature6: "Unlimited Access to all AI features",
  },
];
